In sklearn knn documentation, we can able to find each and everything, like knn ball tree, k dimensional tree, so on.

with sklearn.neighbors.LocalOutlierFactor we can able to detect the outliers

parameters:

(i) n_neighbors = Number of neighbors you want to select (K Value)

(ii) weights = uniform, distance

(iii) algorithm = kd_tree, Ball tree

(iv) metric = minkowski (euclidean distance, manhattan distance)

Also knn is not a machine learning approach, here no cost function, no loss function, no optimization algorithm

Knn is a discuss base approach

If new point is coming, it just calculating the distances and discuss about the new point.

# Classification

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=10000, n_features=50, n_classes=2, random_state=99)

In [3]:
X

array([[ 0.0549804 , -1.73894   , -0.54916057, ...,  0.21323239,
        -0.29719297, -0.59180583],
       [-0.68417316,  0.74039047, -1.1058782 , ..., -0.83213828,
         0.41829136, -0.65001212],
       [ 0.77211261,  0.32166381,  0.93310697, ..., -1.47905372,
        -0.17607756, -0.39075961],
       ...,
       [-1.8064772 , -0.02420355,  0.07454999, ...,  0.41154951,
        -0.1117014 ,  1.03923286],
       [-0.5464854 , -1.8813752 , -2.35661058, ...,  2.10937181,
         0.54416209,  0.41717545],
       [ 0.85065161,  1.45458292, -1.0963427 , ...,  0.45922566,
         1.05812723, -1.82403604]])

In [4]:
y

array([0, 1, 1, ..., 0, 1, 1])

In [5]:
# Model Building

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [6]:
X_train.shape

(6700, 50)

In [7]:
X_test.shape

(3300, 50)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [9]:
knn.score(X_train, y_train)

0.8997014925373135

In [10]:
y_pred = knn.predict(X_test)

In [11]:
y_pred

array([1, 1, 0, ..., 1, 1, 1])

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_score(y_test, y_pred)

0.8296969696969697

In [13]:
# Now use some parameters and fit the model

knn1 = KNeighborsClassifier(algorithm="kd_tree")
knn1.fit(X_train, y_train)

KNeighborsClassifier(algorithm='kd_tree')

In [14]:
knn1.score(X_train, y_train)

0.8997014925373135

In [15]:
y_pred1 = knn1.predict(X_test)

In [16]:
accuracy_score(y_test, y_pred1)

0.8296969696969697

In [28]:
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.81      0.87      0.84      1668
           1       0.86      0.79      0.82      1632

    accuracy                           0.83      3300
   macro avg       0.83      0.83      0.83      3300
weighted avg       0.83      0.83      0.83      3300



In [21]:
knn2 = KNeighborsClassifier(algorithm="ball_tree")
knn2.fit(X_train, y_train)

KNeighborsClassifier(algorithm='ball_tree')

In [22]:
knn2.score(X_train, y_train)

0.8997014925373135

In [23]:
y_pred2 = knn2.predict(X_test)

In [24]:
accuracy_score(y_test, y_pred2)

0.8296969696969697

In [27]:
# Do for regression

                                                                    Completed