In [29]:
import pandas
import numpy
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
# Inside the accuracy score we have different options

In [8]:
X, y = make_classification(n_samples = 1000, n_features=5, random_state=123)
# If we use random state whenever we are running the data will be same.

In [9]:
X

array([[ 0.87728113, -0.59642825,  0.44019839, -0.52108094,  0.31432298],
       [ 0.55856502, -0.41451292,  0.813623  , -0.54325372,  0.14734302],
       [-0.90289911,  0.38303337, -0.71157267, -0.86768895, -0.67394137],
       ...,
       [ 1.7713853 , -0.96445461,  0.99337636,  0.40674576,  0.99881985],
       [-1.19977749,  0.48167954,  1.47831033, -1.31903526, -0.93698258],
       [ 0.33976266, -0.29183452, -0.82476815, -0.57191024,  0.02935597]])

In [10]:
y

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [18]:
X_train.shape

(700, 5)

In [19]:
X_test.shape

(300, 5)

In [20]:
y_train.shape

(700,)

In [21]:
y_test.shape

(300,)

In [22]:
model = LogisticRegression()

In [23]:
# Training the model
model.fit(X_train, y_train) # Here default paremeter was taken.

LogisticRegression()

In [32]:
model.score(X_train, y_train)

0.9428571428571428

In [33]:
# My logistic regression model is able to do 94% of data

# Here my training accuracy is 94%

In [25]:
y_pred = model.predict(X_test)

In [26]:
y_pred

array([0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1])

# This stage is called as the validation stage (because we are testing our model)

In [28]:
# Now checking the accuracy
accuracy_score(y_test, y_pred)

0.97

In [34]:
# Here My testing accuracy is 97%

In [30]:
# Confusion matrix
confusion_matrix(y_test, y_pred)

array([[149,   3],
       [  6, 142]], dtype=int64)

In [31]:
# If training accuracy and testing accuracy have lots of differences, that is a overfitting and underfitting.

In [35]:
# Overfitting

# Train acc is very good
# and Test acc is not good

# Difference between train acc and test acc is 10,20,30,40... (It will fixed by domain experts)
# (for medical data it even 1% variations also blender)
# But vera dataset la 7% variation kooda problem illa

In [36]:
# Underfitting

# Train acc and test acc both are not good

In [ ]:
https://archive.ics.uci.edu/ml/datasets/census+income
https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients

# Do it on Jupyter Notebook

Perform proper EDA

Do Feature engineering and Preprocessing what is required according to the dataset

Model Creation with logistic regression and perform hyper parameter tuning

evaluating the model and print all the scores and check with auc, roc score as well.

now give the conclusion which metrics is correct according to the problem statement

# End-To-End Project

They gave the documentation, check that on resource section.

Dataset will be available in resource section

you need to perform detail eda

you need to complete a feature engineering

train the model

create a complete pipeline with modular coding (training pipeline and prediction pipeline)

you can create one more route in app.py file for the training also

you need to deploy it (aws and azure)

git/github

docker

any database you can integrate (optional)

you can config s3 bucket (optional)